/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTB17 (number 63), J1[4]/U7[24]/D1/UART0_TX/FXIO_D17/UART1_TX_TGTMCU
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_TX_PERIPHERAL LPUART0
/*!
 * @brief Signal name */
#define BOARD_INITPINS_DEBUG_UART_TX_SIGNAL TX
/*!
 * @brief Routed pin name */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_NAME LPUART0_TX
/*!
 * @brief Label */
#define BOARD_INITPINS_DEBUG_UART_TX_LABEL "J1[4]/U7[24]/D1/UART0_TX/FXIO_D17/UART1_TX_TGTMCU"
/*!
 * @brief Identifier */
#define BOARD_INITPINS_DEBUG_UART_TX_NAME "DEBUG_UART_TX"

/* Symbols to be used with PORT driver */
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTB
/*!
 * @brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 17U
/*!
 * @brief PORT pin mask */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 17U)
/* @} */

/*! @name PORTE0 (number 1), U2[3]/INT1_21002
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_GYRO_INT1_PERIPHERAL GPIOE         /*!<@brief Peripheral name */
#define BOARD_INITPINS_GYRO_INT1_SIGNAL GPIO              /*!<@brief Signal name */
#define BOARD_INITPINS_GYRO_INT1_CHANNEL 0                /*!<@brief Signal channel */
#define BOARD_INITPINS_GYRO_INT1_PIN_NAME PTE0            /*!<@brief Routed pin name */
#define BOARD_INITPINS_GYRO_INT1_LABEL "U2[3]/INT1_21002" /*!<@brief Label */
#define BOARD_INITPINS_GYRO_INT1_NAME "GYRO_INT1"         /*!<@brief Identifier */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GYRO_INT1_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GYRO_INT1_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_GYRO_INT1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GYRO_INT1_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GYRO_INT1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GYRO_INT1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTE1 (number 2), U2[2]/INT2_21002
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_GYRO_INT2_PERIPHERAL GPIOE         /*!<@brief Peripheral name */
#define BOARD_INITPINS_GYRO_INT2_SIGNAL GPIO              /*!<@brief Signal name */
#define BOARD_INITPINS_GYRO_INT2_CHANNEL 1                /*!<@brief Signal channel */
#define BOARD_INITPINS_GYRO_INT2_PIN_NAME PTE1            /*!<@brief Routed pin name */
#define BOARD_INITPINS_GYRO_INT2_LABEL "U2[2]/INT2_21002" /*!<@brief Label */
#define BOARD_INITPINS_GYRO_INT2_NAME "GYRO_INT2"         /*!<@brief Identifier */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GYRO_INT2_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_GYRO_INT2_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_GYRO_INT2_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_GYRO_INT2_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GYRO_INT2_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GYRO_INT2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTA17 (number 47), J3[13]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_SW_PIN_PERIPHERAL GPIOA                  /*!<@brief Peripheral name */
#define BOARD_INITPINS_SW_PIN_SIGNAL GPIO                       /*!<@brief Signal name */
#define BOARD_INITPINS_SW_PIN_CHANNEL 17                        /*!<@brief Signal channel */
#define BOARD_INITPINS_SW_PIN_PIN_NAME PTA17                    /*!<@brief Routed pin name */
#define BOARD_INITPINS_SW_PIN_LABEL "J3[13]"                    /*!<@brief Label */
#define BOARD_INITPINS_SW_PIN_NAME "SW_PIN"                     /*!<@brief Identifier */
#define BOARD_INITPINS_SW_PIN_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW_PIN_FGPIO FGPIOA                      /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_SW_PIN_GPIO GPIOA                        /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW_PIN_GPIO_PIN 17U                      /*!<@brief GPIO pin number */
#define BOARD_INITPINS_SW_PIN_GPIO_PIN_MASK (1U << 17U)         /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SW_PIN_PORT PORTA                        /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW_PIN_PIN 17U                           /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW_PIN_PIN_MASK (1U << 17U)              /*!<@brief PORT pin mask */
                                                                /* @} */

/*! @name PORTC4 (number 76), LEDRGB_GREEN
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LED_GREEN_PERIPHERAL TPM0          /*!<@brief Peripheral name */
#define BOARD_INITPINS_LED_GREEN_SIGNAL CH                /*!<@brief Signal name */
#define BOARD_INITPINS_LED_GREEN_CHANNEL 3                /*!<@brief Signal channel */
#define BOARD_INITPINS_LED_GREEN_PIN_NAME TPM0_CH3        /*!<@brief Routed pin name */
#define BOARD_INITPINS_LED_GREEN_LABEL "LEDRGB_GREEN"     /*!<@brief Label */
#define BOARD_INITPINS_LED_GREEN_NAME "LED_GREEN"         /*!<@brief Identifier */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTE29 (number 26), LEDRGB_RED
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LED_RED_PERIPHERAL TPM0           /*!<@brief Peripheral name */
#define BOARD_INITPINS_LED_RED_SIGNAL CH                 /*!<@brief Signal name */
#define BOARD_INITPINS_LED_RED_CHANNEL 2                 /*!<@brief Signal channel */
#define BOARD_INITPINS_LED_RED_PIN_NAME TPM0_CH2         /*!<@brief Routed pin name */
#define BOARD_INITPINS_LED_RED_LABEL "LEDRGB_RED"        /*!<@brief Label */
#define BOARD_INITPINS_LED_RED_NAME "LED_RED"            /*!<@brief Identifier */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTE31 (number 28), LEDRGB_BLUE
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LED_BLUE_PERIPHERAL TPM0           /*!<@brief Peripheral name */
#define BOARD_INITPINS_LED_BLUE_SIGNAL CH                 /*!<@brief Signal name */
#define BOARD_INITPINS_LED_BLUE_CHANNEL 4                 /*!<@brief Signal channel */
#define BOARD_INITPINS_LED_BLUE_PIN_NAME TPM0_CH4         /*!<@brief Routed pin name */
#define BOARD_INITPINS_LED_BLUE_LABEL "LEDRGB_BLUE"       /*!<@brief Label */
#define BOARD_INITPINS_LED_BLUE_NAME "LED_BLUE"           /*!<@brief Identifier */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 31U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
